# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 14:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_to', models.DateField(verbose_name='To')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Value')),
            ],
            options={
                'verbose_name_plural': 'Results',
                'verbose_name': 'Result',
            },
        ),
    ]
